
# fzf oh-my-zsh plugin needs fzf to be installed already.
# FZF installation
export FZF_BASE=$HOME/.fzf
if [ ! -d "$FZF_BASE" ]; then
  git clone --depth 1 https://github.com/junegunn/fzf.git $FZF_BASE
  $FZF_BASE/install --all
fi

# Antigen installation
[ ! -f ~/.antigen.zsh ] && curl -L git.io/antigen > ~/.antigen.zsh
source ~/.antigen.zsh

source ~/.zsh/functions.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/exports.zsh
source ~/.zsh/bindings.zsh
source ~/.zsh/history.zsh
source ~/.zsh/hooks.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle command-not-found
antigen bundle fzf
antigen bundle djui/alias-tips

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zdharma-continuum/fast-syntax-highlighting
antigen bundle zsh-users/zsh-completions
# antigen bundle zsh-users/zsh-history-substring-search

# Load the theme.
antigen theme robbyrussell

# Tell Antigen that you're done.
antigen apply

source ~/.fzf.zsh
# Local configuration
[ -f ~/.zshrc.local ] && source ~/.zshrc.local

