# fzf oh-my-zsh plugin needs fzf to be installed already.
# FZF installation
export FZF_BASE=$HOME/.fzf
if [ ! -d "$FZF_BASE" ]; then
  git clone --depth 1 https://github.com/junegunn/fzf.git $FZF_BASE
  $FZF_BASE/install --all
fi

# Antigen installation
[ ! -f ~/.antigen.zsh ] && curl -L git.io/antigen > ~/.antigen.zsh
source ~/.antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Load the theme.
antigen theme robbyrussell

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle command-not-found
antigen bundle fzf
antigen bundle djui/alias-tips
antigen bundle zsh-bat

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions

# Below should be at the end
# antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zdharma-continuum/fast-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search

# Tell Antigen that you're done.
antigen apply

source ~/.zsh/functions.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/exports.zsh
source ~/.zsh/history.zsh
source ~/.zsh/hooks.zsh
source ~/.zsh/bindings.zsh

[[ ! -f ~/.fzf.zsh ]] || source ~/.fzf.zsh

# Local configuration
[ -f ~/.zshrc.local ] && source ~/.zshrc.local
[ -f ~/.zshrc.secure ] && source ~/.zshrc.secure

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
