#!/usr/bin/env bash
[[ -z "$PS1" ]] && return

# If not running interactively, don't do anything
case $- in
  *i*) ;;
    *) return;;
esac

# BASH configuration directory
BASH_D="$HOME/.bash"

for cust_cfg in "${BASH_D}"/custom/*.bash; do
	[ -r "$cust_cfg" ] && [ -f "$cust_cfg" ] && source "$cust_cfg"
done
unset cust_cfg

# Load all functions
for func_defs in "$BASH_D"/custom/functions/*.bash; do
	[ -r "$func_defs"  ] && [ -f "$func_defs"  ] && source "$func_defs";
done
unset func_defs

# Load host specific configuration
hostname="$(hostname)"
for host_cfg in "$BASH_D"/custom/hosts/*.bash; do
	host_pattern="$(basename "$host_cfg" .bash)"
	if [[ "$hostname" = *$host_pattern* ]]; then
		[ -r "$host_cfg" ] && [ -f "$host_cfg" ] && source "$host_cfg"
	fi
done
unset hostname

# Load the private bash config files
CUSTOM="${HOME}/.bashrc.local"
if [[ -e "${CUSTOM}" ]]; then
	# shellcheck disable=SC1090
	source $CUSTOM
fi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
